### ISSUE TITLE
[Bug] Alt + X shows take lanes or does nothing

### ISSUE THREAD

**Issue by enoversum** [LiveEnhancementSuite/LESforWindows#14]
I don't remember when it started, but recently, when I try to use **Alt + X** to clean a track, it would either create or delete a take lane (or only show them?). Once I use the shortcut, the take lanes show up, and I believe there is an empty one created, hard to tell when suddenly the lanes reveal themselves 🙂. 
I suppose it's only on tracks that already have takes, but I remember it's acting similarly weird on tracks inside groups, deleting and/or duplicating tracks.
Is this something known? Should I investigate further?

Edit: Okay, tried it out again. What Alt + X does is adding and quickly deleting a take lane again (the undo history revealed that). On audio tracks, you just see a quick glitch (something is popping up and disappearing again), on MIDI tracks as well, plus the track lanes stay visible.

**Comment by Inversil** [comment]
hmm that seems weird. Some of the shortcuts rely on language specific strings to be present, are you using Live in a language other than English?

**Comment by enoversum** [comment]
Hey @Inversil - I am on a German system. While you English keyboard users often get shortcuts that are not accessible for us, because we can't use modifiers and another modifier to get to the character, in this case it had worked before, but now since 11 ceases to like me :).

**Comment by Inversil** [comment]
ohh they reason I bring it up because it requires certain strings *in live*. if you change ableton live's language to english it *should* work. keyboard layout doesn't matter

**Comment by enoversum** [comment]
@Inversil Ah, I get it, I just mixed two things up here. Unfortunately, even an English (US) interface doesn't let me Alt + X properly, I just tried it. I also tried to remove any key bindings I did in Live, to no avail. The fanciest change to Live is actually LES for me, nothing really added on top of that which might interfere.

**Comment by Inversil** [comment]
hello! sorry for taking so long to get back to you.

You're right! it actually happens to me too!! I know why this is happening; I need to add an exception to the shortcut for live 11 users. I can't believe this took me so long to find. I was so sure that it was working correctly as I've used it many times... but I suppose not recently?
Thanks a lot for your report! I will include the fix when I get around to updating :-)

**Comment by enoversum** [comment]
@Inversil Haha, no worries, you don't have to be quick, it's enough that LES is helping me navigate Live much quicker every day, and you're doing it in your free time!

Wonderful you finally ‘found’ the bug as well 🤣. And glad you're working on a fix, whenever you'll find the time!

**Comment by dioneno** [comment]
Any news òn how long this fix gonna take?

**Comment by Inversil** [comment]
finally got around to updating this tool a bit! this should work now!!
let me know. 

Best way to beta test is to clone the repo and run the .ahk file after installing autohotkey. I will make a proper build later and update the website with it some other time. Thanks a lot!

https://github.com/LiveEnhancementSuite/LESforWindows/commit/1db45ce804466a7fc6e989219a08afc24bbd8d59

**Comment by dioneno** [comment]
This still does not work for me with Release 1.3.5 and Live 11.1.1 - Am I missing something?

**Comment by dioneno** [comment]
OK nvm I am using too many return tracks, so that option on the list is missing. 
![image](https://user-images.githubusercontent.com/99808608/185949233-52d2c0f8-72e5-419e-9f50-9789176c7be2.png)
Any workarounds for this, except deleting one of my return tracks?

**Comment by Inversil** [comment]
Hey! Thanks for reporting this. I’m not sure if there is a way to detect how many return tracks someone has… but I have one idea: does an option to create return tracks get greyed out in the dropdown menus at the top of the window when you reach the limit? Under “create”

**Comment by dioneno** [comment]
Yes there is a greyed out option: 
![image](https://user-images.githubusercontent.com/99808608/185953559-9bbfe79d-c4e9-4ae9-8aef-2a39944972fb.png)

**Comment by Inversil** [comment]
Hmmm.. I guess the solution for this would be to check if this option is greyed out and then do the macro differently. But I’ll have to implement that myself. I’ll change the flags so I do it when I get around to making the next update :-)

**Comment by dioneno** [comment]
I appreciate your work 🙏

**Comment by Inversil** [comment]
Oh yeah, if anyone makes a pull request for this I will merge it immediately! It might be a while until I can make another update myself

**Comment by Zylvian** [comment]
In Live 11, Alt+X causes LES to freeze the the track I'm currently on.

**Comment by waynehuang3440** [comment]
for some reason this problem still exists.

if you want, you can use resource hacker to fix it yourself.
find the autohotkey script and use Ctrl+F and F3 to find the "cleartrack" section.
![image](https://github.com/LiveEnhancementSuite/LESforWindows/assets/72854267/65ff8bd8-c151-43ff-ab58-2b1c3e281a5d)
i changed {down 12} it to {s} to make it jump directly to the "select track content" and disabled sleep for faster operation.
